In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import clear_output
from time import sleep
import os

In [11]:
csv_path = 'data/via_export.csv'
csv_data = pd.read_csv(csv_path)
csv_path_final = 'testimgface.csv'

In [7]:
csv_data.head()

,filename,file_size,file_attributes,region_count,region_id,region_shape_attributes,region_attributes
0,opencv_frame_0.jpg,21091,{},16,0,"{""name"":""point"",""cx"":70,""cy"":110}","{""1"":""Left eye left\n"","""":""Left eye left""}"
1,opencv_frame_0.jpg,21091,{},16,1,"{""name"":""point"",""cx"":94,""cy"":112}","{"""":""Left eye middle""}"
2,opencv_frame_0.jpg,21091,{},16,2,"{""name"":""point"",""cx"":116,""cy"":115}","{"""":""Left eye right""}"
3,opencv_frame_0.jpg,21091,{},16,3,"{""name"":""point"",""cx"":184,""cy"":121}","{"""":""Right eye left""}"
4,opencv_frame_0.jpg,21091,{},16,4,"{""name"":""point"",""cx"":203,""cy"":122}","{"""":""Right eye middle""}"

In [8]:
csv_data['cx'] = csv_data.region_shape_attributes.str.extract('name":"point","cx":([^,"cy"]*)')
csv_data['cy'] = csv_data.region_shape_attributes.str.extract(',"cy":([^}]*)')
csv_data.head()

,filename,file_size,file_attributes,region_count,region_id,region_shape_attributes,region_attributes,cx,cy
0,opencv_frame_0.jpg,21091,{},16,0,"{""name"":""point"",""cx"":70,""cy"":110}","{""1"":""Left eye left\n"","""":""Left eye left""}",70,110
1,opencv_frame_0.jpg,21091,{},16,1,"{""name"":""point"",""cx"":94,""cy"":112}","{"""":""Left eye middle""}",94,112
2,opencv_frame_0.jpg,21091,{},16,2,"{""name"":""point"",""cx"":116,""cy"":115}","{"""":""Left eye right""}",116,115
3,opencv_frame_0.jpg,21091,{},16,3,"{""name"":""point"",""cx"":184,""cy"":121}","{"""":""Right eye left""}",184,121
4,opencv_frame_0.jpg,21091,{},16,4,"{""name"":""point"",""cx"":203,""cy"":122}","{"""":""Right eye middle""}",203,122

In [9]:
pivoted = csv_data.pivot(index='filename', columns='region_id', values=['cx','cy'])

In [12]:
pivoted.to_csv(csv_path_final, index = True, header=True)

In [13]:
csv_final = pd.read_csv(csv_path_final)  

csv_final = csv_final[['cx', 'cy', 'cx.1', 'cy.1', 'cx.2', 'cy.2', 'cx.3', 'cy.3', 'cx.4', 'cy.4', 'cx.5', 'cy.5', 'cx.6', 'cy.6', 'cx.7', 'cy.7', 'cx.8', 'cy.8', 'cx.9', 'cy.9', 'cx.10', 'cy.10', 'cx.11', 'cy.11', 'cx.12', 'cy.12', 'cx.13', 'cy.13', 'cx.14', 'cy.14', 'cx.15', 'cy.15', 'Unnamed: 0']]
csv_final.rename(columns={'cx': "0x", 'cy': '0y', 'cx.1': '1x', 'cy.1': '1y', 'cx.2': '2x', 'cy.2': '2y', 'cx.3': '3x', 'cy.3': '3y', 'cx.4': '4x', 'cy.4': '4y', 'cx.5': '5x', 'cy.5': '5y', 'cx.6': '6x', 'cy.6': '6y', 'cx.7': '7x', 'cy.7': '7y', 'cx.8': '8x', 'cy.8': '8y', 'cx.9': '9x', 'cy.9': '9y', 'cx.10': '10x', 'cy.10': '10y', 'cx.11': '11x', 'cy.11': '11y', 'cx.12': '12x', 'cy.12': '12y', 'cx.13': '13x', 'cy.13': '13y', 'cx.14': '14x', 'cy.14': '14y', 'cx.15': '15x', 'cy.15': '15y', 'Unnamed: 0': 'image'}, inplace=True)

In [14]:
csv_final.drop(index=[0,1], inplace=True)

In [15]:
csv_final.to_csv (csv_path_final, index = True, header=True)

In [17]:
df = pd.read_csv(csv_path_final)
first_column = df.columns[0]
df = df.drop([first_column], axis=1)

In [18]:
df.to_csv(csv_path_final, index=False)
print(df)

      0x     0y     1x     1y     2x     2y     3x     3y     4x     4y  ...  \
0   70.0  110.0   94.0  112.0  116.0  115.0  184.0  121.0  203.0  122.0  ...
1   70.0  110.0   92.0  111.0  117.0  116.0  180.0  123.0  199.0  124.0  ...
2   35.0  109.0   64.0  104.0   87.0  111.0  172.0  127.0  201.0  126.0  ...
3   36.0  108.0   66.0  101.0   87.0  109.0  172.0  126.0  202.0  127.0  ...
4   40.0  105.0   64.0  104.0   85.0  111.0  175.0  127.0  199.0  127.0  ...
5   41.0  106.0   66.0  104.0   86.0  111.0  176.0  125.0  199.0  126.0  ...
6   42.0   81.0   76.0   64.0  109.0   62.0  276.0   46.0  297.0   42.0  ...
7   70.0  111.0   91.0  114.0  113.0  116.0  180.0  119.0  202.0  119.0  ...
8   75.0  114.0  100.0  114.0  118.0  115.0  184.0  117.0  206.0  116.0  ...
9   75.0  110.0   95.0  113.0  119.0  118.0  183.0  120.0  205.0  124.0  ...
10  68.0  106.0   93.0  109.0  115.0  113.0  179.0  121.0  201.0  123.0  ...
11  72.0  118.0   97.0  118.0  117.0  119.0  181.0  119.0  204.0  120.0  ...
12  76.0  113.0  100.0  113.0  120.0  114.0  187.0  113.0  207.0  114.0  ...
13  65.0  110.0   88.0  111.0  109.0  111.0  179.0  115.0  201.0  120.0  ...
14  71.0  109.0   96.0  110.0  122.0  112.0  188.0  125.0  209.0  130.0  ...
15  60.0  114.0   89.0  117.0  115.0  117.0  183.0  124.0  206.0  129.0  ...
16  71.0  114.0   95.0  114.0  120.0  118.0  183.0  120.0  205.0  121.0  ...
17  66.0  108.0   94.0  108.0  116.0  110.0  184.0  113.0  207.0  116.0  ...
18  61.0  112.0   87.0  111.0  109.0  115.0  180.0  119.0  204.0  121.0  ...
19  61.0  110.0   85.0  112.0  108.0  114.0  175.0  119.0  198.0  122.0  ...
20  79.0  112.0   98.0  113.0  120.0  113.0  184.0  113.0  206.0  115.0  ...
21  65.0  110.0   92.0  110.0  119.0  115.0  183.0  121.0  208.0  125.0  ...
22  64.0  113.0   93.0  114.0  114.0  114.0  179.0  118.0  205.0  123.0  ...
23  64.0  114.0   93.0  114.0  115.0  115.0  179.0  118.0  200.0  123.0  ...
24  62.0  111.0   90.0  110.0  112.0  112.0  184.0  120.0  206.0  124.0  ...
25  61.0  113.0   87.0  111.0  113.0  113.0  182.0  117.0  206.0  120.0  ...
26  58.0  111.0   87.0  110.0  112.0  113.0  182.0  119.0  205.0  124.0  ...
27  69.0  112.0   93.0  112.0  115.0  114.0  180.0  117.0  206.0  124.0  ...
28  72.0  111.0   94.0  115.0  118.0  116.0  190.0  120.0  212.0  126.0  ...
29  70.0  126.0   90.0  125.0  113.0  121.0  177.0  126.0  196.0  133.0  ...
30  58.0  120.0   86.0  122.0  110.0  122.0  177.0  128.0  201.0  133.0  ...
31  65.0  119.0   91.0  121.0  114.0  122.0  180.0  125.0  201.0  127.0  ...
32  68.0  115.0   91.0  115.0  114.0  118.0  179.0  123.0  204.0  126.0  ...
33  73.0  115.0   92.0  114.0  114.0  117.0  181.0  121.0  206.0  123.0  ...
34  78.0  117.0  101.0  117.0  120.0  119.0  180.0  122.0  203.0  122.0  ...
35  76.0  113.0   98.0  115.0  115.0  118.0  179.0  120.0  201.0  120.0  ...
36  80.0  106.0  103.0  111.0  120.0  117.0  180.0  123.0  202.0  125.0  ...
37  68.0  107.0   94.0  111.0  115.0  111.0  179.0  116.0  199.0  122.0  ...
38  67.0  111.0   90.0  112.0  106.0  112.0  171.0  112.0  190.0  110.0  ...
39  77.0  117.0   98.0  118.0  117.0  120.0  181.0  116.0  204.0  115.0  ...
40  79.0  107.0   97.0  109.0  118.0  113.0  181.0  116.0  201.0  115.0  ...
41  76.0  104.0   95.0  106.0  112.0  109.0  183.0  118.0  205.0  120.0  ...
42  78.0  100.0   98.0  105.0  119.0  106.0  185.0  119.0  202.0  120.0  ...
43  70.0  120.0   92.0  119.0  111.0  117.0  175.0  115.0  198.0  118.0  ...
44  59.0  129.0   87.0  129.0  109.0  126.0  174.0  117.0  200.0  119.0  ...
45  77.0  112.0   94.0  113.0  112.0  113.0  177.0  116.0  198.0  122.0  ...
46  79.0  105.0  100.0  107.0  119.0  108.0  180.0  117.0  203.0  125.0  ...
47  76.0  121.0   98.0  123.0  121.0  120.0  172.0  111.0  202.0  114.0  ...
48  65.0  110.0   88.0  111.0  107.0  114.0  178.0  122.0  200.0  126.0  ...
49  73.0  125.0   98.0  125.0  119.0  119.0  174.0  112.0  203.0  119.0  ...
50  73.0  104.0   99.0  108.0  122.0  112.0  183.0  120.0  206.0  122.0  ...
51  67.0  112.0   90.0  113.0  116.0  116.0  180.0  119.0  207.0  122.0  ...
52  63.0  119.0   87.0  119.0  109.0  119.0  178.0  116.0  201.0  116.0  ...
53  64.0  108.0   98.0  111.0  117.0  114.0  180.0  124.0  205.0  131.0  ...
54  72.0  114.0   98.0  117.0  119.0  119.0  186.0  120.0  207.0  121.0  ...
55  67.0  108.0   91.0  111.0  110.0  116.0  180.0  122.0  204.0  123.0  ...
56  70.0  110.0   89.0  110.0  115.0  114.0  183.0  120.0  204.0  125.0  ...
57  65.0  111.0   89.0  114.0  113.0  116.0  181.0  121.0  206.0  122.0  ...
58  63.0  111.0   93.0  113.0  114.0  115.0  178.0  120.0  202.0  123.0  ...
59  51.0  117.0   73.0  118.0   92.0  118.0  169.0  129.0  192.0  132.0  ...

      11y    12x    12y    13x    13y   14x    14y   15x    15y  \
0   247.0  208.0  283.0  136.0  297.0  46.0  283.0  14.0  243.0
1   245.0  204.0  280.0  136.0  297.0  49.0  281.0  20.0  244.0
2   285.0  225.0  298.0  143.0  298.0  20.0  298.0   1.0  271.0
3   282.0  225.0  298.0  138.0  298.0  27.0  298.0   2.0  273.0
4   291.0  221.0  299.0  139.0  298.0  30.0  292.0   5.0  279.0
5   292.0  222.0  296.0  146.0  297.0  14.0  293.0   4.0  279.0
6   251.0  298.0  274.0  162.0  297.0   9.0  285.0   0.0  266.0
7   242.0  222.0  277.0  139.0  298.0  59.0  285.0  34.0  250.0
8   252.0  230.0  284.0  141.0  294.0  77.0  288.0  57.0  256.0
9   272.0  215.0  290.0  136.0  297.0  61.0  287.0  36.0  252.0
10  256.0  204.0  282.0  131.0  296.0  49.0  279.0  21.0  245.0
11  242.0  228.0  275.0  144.0  298.0  82.0  290.0  58.0  251.0
12  233.0  240.0  274.0  154.0  295.0  88.0  287.0  65.0  248.0
13  265.0  228.0  288.0  128.0  298.0  37.0  292.0  23.0  264.0
14  276.0  223.0  295.0  121.0  298.0  38.0  290.0  20.0  257.0
15  262.0  225.0  288.0  140.0  299.0  37.0  293.0  18.0  264.0
16  256.0  228.0  281.0  142.0  296.0  47.0  286.0  28.0  259.0
17  243.0  224.0  278.0  137.0  297.0  51.0  282.0  26.0  255.0
18  238.0  222.0  272.0  138.0  297.0  39.0  277.0  19.0  242.0
19  240.0  216.0  275.0  135.0  298.0  29.0  279.0  15.0  242.0
20  247.0  237.0  279.0  148.0  296.0  82.0  285.0  63.0  254.0
21  241.0  225.0  278.0  135.0  298.0  22.0  281.0  12.0  251.0
22  264.0  223.0  290.0  141.0  294.0  44.0  294.0  23.0  264.0
23  252.0  229.0  284.0  138.0  297.0  46.0  292.0  24.0  268.0
24  276.0  231.0  297.0  137.0  297.0  46.0  298.0  19.0  284.0
25  264.0  234.0  294.0  142.0  296.0  42.0  298.0  16.0  278.0
26  261.0  235.0  292.0  149.0  298.0  42.0  297.0  18.0  273.0
27  264.0  230.0  291.0  140.0  294.0  53.0  294.0  25.0  269.0
28  257.0  245.0  283.0  141.0  298.0  47.0  287.0  31.0  261.0
29  278.0  228.0  298.0  139.0  297.0  34.0  298.0  20.0  280.0
30  272.0  230.0  297.0  139.0  298.0  37.0  299.0  19.0  276.0
31  261.0  219.0  294.0  135.0  298.0  66.0  299.0  32.0  280.0
32  270.0  219.0  299.0  133.0  297.0  59.0  299.0  32.0  280.0
33  267.0  215.0  297.0  147.0  297.0  76.0  298.0  43.0  274.0
34  248.0  209.0  288.0  141.0  299.0  80.0  291.0  45.0  247.0
35  242.0  209.0  276.0  134.0  297.0  73.0  276.0  47.0  240.0
36  250.0  187.0  280.0  128.0  295.0  72.0  278.0  40.0  236.0
37  243.0  212.0  277.0  133.0  297.0  56.0  284.0  23.0  250.0
38  224.0  200.0  266.0  139.0  297.0  83.0  276.0  49.0  227.0
39  243.0  225.0  276.0  154.0  298.0  85.0  276.0  59.0  236.0
40  247.0  211.0  275.0  144.0  296.0  78.0  274.0  51.0  231.0
41  254.0  192.0  280.0  125.0  298.0  65.0  272.0  34.0  227.0
42  245.0  190.0  276.0  126.0  295.0  58.0  269.0  28.0  226.0
43  240.0  210.0  271.0  145.0  299.0  56.0  283.0  28.0  247.0
44  243.0  233.0  276.0  156.0  296.0  81.0  298.0  48.0  276.0
45  243.0  205.0  273.0  133.0  299.0  74.0  268.0  53.0  235.0
46  253.0  212.0  276.0  132.0  296.0  66.0  268.0  48.0  224.0
47  236.0  216.0  266.0  151.0  295.0  93.0  273.0  65.0  244.0
48  274.0  203.0  297.0  139.0  298.0  42.0  298.0   6.0  264.0
49  231.0  223.0  270.0  157.0  296.0  86.0  283.0  52.0  246.0
50  266.0  195.0  299.0  130.0  299.0  61.0  287.0  29.0  238.0
51  258.0  213.0  297.0  147.0  299.0  61.0  299.0  20.0  256.0
52  264.0  225.0  299.0  152.0  298.0  38.0  297.0  29.0  279.0
53  274.0  208.0  298.0  122.0  299.0  50.0  297.0   9.0  265.0
54  260.0  208.0  298.0  120.0  297.0  52.0  294.0  28.0  254.0
55  248.0  208.0  292.0  140.0  297.0  63.0  296.0  24.0  260.0
56  267.0  204.0  298.0  128.0  299.0  54.0  298.0  24.0  264.0
57  262.0  209.0  294.0  137.0  298.0  56.0  295.0  19.0  266.0
58  257.0  202.0  297.0  138.0  298.0  53.0  298.0  18.0  258.0
59  278.0  208.0  298.0  145.0  299.0  32.0  296.0   2.0  271.0

                  image
0    opencv_frame_0.jpg
1    opencv_frame_1.jpg
2   opencv_frame_10.jpg
3   opencv_frame_11.jpg
4   opencv_frame_12.jpg
5   opencv_frame_13.jpg
6   opencv_frame_14.jpg
7    opencv_frame_2.jpg
8   opencv_frame_23.jpg
9   opencv_frame_24.jpg
10  opencv_frame_26.jpg
11   opencv_frame_3.jpg
12   opencv_frame_4.jpg
13  opencv_frame_40.jpg
14  opencv_frame_41.jpg
15  opencv_frame_45.jpg
16  opencv_frame_46.jpg
17  opencv_frame_47.jpg
18  opencv_frame_48.jpg
19  opencv_frame_49.jpg
20   opencv_frame_5.jpg
21  opencv_frame_50.jpg
22  opencv_frame_54.jpg
23  opencv_frame_55.jpg
24  opencv_frame_56.jpg
25  opencv_frame_57.jpg
26  opencv_frame_58.jpg
27  opencv_frame_59.jpg
28   opencv_frame_6.jpg
29  opencv_frame_60.jpg
30  opencv_frame_61.jpg
31  opencv_frame_62.jpg
32  opencv_frame_63.jpg
33  opencv_frame_64.jpg
34  opencv_frame_65.jpg
35  opencv_frame_66.jpg
36  opencv_frame_67.jpg
37   opencv_frame_7.jpg
38  opencv_frame_70.jpg
39  opencv_frame_71.jpg
40  opencv_frame_72.jpg
41  opencv_frame_73.jpg
42  opencv_frame_74.jpg
43  opencv_frame_75.jpg
44  opencv_frame_76.jpg
45  opencv_frame_77.jpg
46  opencv_frame_78.jpg
47  opencv_frame_79.jpg
48   opencv_frame_8.jpg
49  opencv_frame_80.jpg
50  opencv_frame_81.jpg
51  opencv_frame_82.jpg
52  opencv_frame_83.jpg
53  opencv_frame_84.jpg
54  opencv_frame_85.jpg
55  opencv_frame_86.jpg
56  opencv_frame_87.jpg
57  opencv_frame_88.jpg
58  opencv_frame_89.jpg
59   opencv_frame_9.jpg

[60 rows x 33 columns]