In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import clear_output
from time import sleep
import os

In [5]:
csv_path = 'trainimgface.csv'
csv_data = pd.read_csv(csv_path)  
csv_path_final = 'testimgface.csv'

In [8]:
csv_data.head()

,0x,0y,1x,1y,2x,2y,3x,3y,4x,4y,...,11y,12x,12y,13x,13y,14x,14y,15x,15y,image
0,130,127,146,126,156,127,193,145,203,148,...,181,195,217,164,247,111,209,78,182,trainimg_1.jpg
1,108,163,114,155,119,151,145,131,152,123,...,162,220,209,169,248,131,224,120,195,trainimg_2.jpg
2,103,135,115,131,126,133,166,131,178,126,...,164,214,200,162,237,108,214,96,176,trainimg_3.jpg
3,98,137,107,133,122,129,162,131,174,125,...,166,204,218,155,254,101,220,90,185,trainimg_4.jpg
4,103,145,113,135,123,135,155,129,164,120,...,175,224,210,170,251,122,215,111,181,trainimg_5.jpg